### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by LucasColomer** [dockwa/EmailPicker#1]
Hi, actually we haven't access to 1.4.0 version with cocoapods. The last version available is the 1.3.0 [https://cocoapods.org/pods/EmailPicker](url).

It's work on 1.4.0 if we replace the number version with the tag of the release and the git hub repository URL.

Can you add it to the cocoapods repository ? 

Thanks for your this pod !

**Comment by christianhatch** [comment]
I have pushed version 1.5.0 which supports Swift 5 to Cocoapods
